---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: web
  annotatios:
    alb.ingress.kubernetes.io/healthcheck-path:"/"
  labels:
    app: nginx-fargate
spec:
  selector:
    app: nginx-fargate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
