---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-fargate
  template:
    metadata:
      labels:
        app: nginx-fargate
      containers:
      - image: 194453983284.dkr.ecr.ap-northeast-1.amazonaws.com/last-nginx:latest
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
      nodeSelector:
        app: nginx-fargate
