#nginx-deploy.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 194453983284.dkr.ecr.ap-northeast-1.amazonaws.com/last-nginx:latest
        name: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      nodeSelector:
        app: nginx
